R""(
const int ANALYSIS_GROUP_SIZE = 8;
const int ANALYSIS_PER_THREAD_AREA = 4;
const int ANALYSIS_PER_THREAD_BITS = 2;

const int CALC_GROUP_SIZE = 8;
const int LIGHT_MAX_RANGE_SLOTS = LIGHT_MAX_RANGETi / ANALYSIS_GROUP_SIZE / ANALYSIS_PER_THREAD_AREA;

const int MAX_LIGHTS_PER_SLOT = ANALYSIS_GROUP_SIZE * ANALYSIS_GROUP_SIZE;

)""