#ifndef BUFFERS_GLSL
#define BUFFERS_GLSL
//STORAGE BUFFERS
const int STRG_BUF_PLAYER = 10;
const int STRG_BUF_ACTIVECHUNKS = 11;
const int STRG_BUF_EXTERNALLIGHTS = 12;

//UNIFORM BUFFERS
const int UNIF_BUF_VIEWPORT_MATRIX = 13;
const int UNIF_BUF_PLAYERMOVEMENT = 14;
const int UNIF_BUF_GENERATION = 15;
const int UNIF_BUF_WORLDDRAWER = 16;
const int UNIF_BUF_WORLDDYNAMICS = 17;
const int UNIF_BUF_TILEPROPERTIES = 18;
#endif