/**
 *  @author     Dubsky Tomas
 */
#version 460
#include <RealWorld/constants/Tile.glsl>
#include <RealWorld/constants/Light.glsl>
#include <RealWorld/drawing/shaders/AnalysisPC.glsl>
#include <RealWorld/drawing/shaders/analysisPll.glsl>
#include <RealWorld/drawing/shaders/ExternalLightsSB.glsl>

layout (local_size_x = k_addExternalLightsGroupSize,
        local_size_y = 2,
        local_size_z = 2
) in;

layout (set = 0, binding = k_lightXluImageBinding, r32ui)
    uniform restrict uimage2DArray u_lightXluImage[k_lightCellSizeCount];

const int k_toUnitBits = k_lightMinCellTiBitShift + 2;
const vec2 k_toUnitScale = vec2(1.0, 1.0) / float(k_lightMinCellTi) / TilePx;

vec4 lightOfThisUnit(vec4 lightTotal, vec2 lightPosPx, vec2 relUn){
    vec2 posUnFract = fract(lightPosPx * k_toUnitScale + relUn);
    vec2 portion = vec2(1.0) - abs(posUnFract - relUn);
    return lightTotal * portion.x * portion.y;
}

void addAtomically(
    uint mipIndex, uint arrayIndex, ivec2 editPos, vec2 addition
) {
    uint last = imageLoad(u_lightXluImage[mipIndex], ivec3(editPos, arrayIndex)).r;
    uint expected;
    do {
        vec2 wantedUnpacked = unpackHalf2x16(last) + addition;
        uint wanted = packHalf2x16(wantedUnpacked);
        expected = last;
        last = imageAtomicCompSwap(
            u_lightXluImage[mipIndex], ivec3(editPos, arrayIndex), expected, wanted
        );
    } while (last != expected);
}

void main(){
    if (gl_GlobalInvocationID.x < p_.lightCount){
        ExternalLight light = b_externalLights.lights[gl_GlobalInvocationID.x];
        ivec2 lightPosPx = light.posPx - p_.addLightOffsetPx;
        ivec2 lightPosUn = lightPosPx >> k_lightMinCellTiBitShift;
        ivec2 editPos = imageSize(u_lightXluImage[0]).xy / 2;//lightPosUn + ivec2(gl_LocalInvocationID.yz);
        bvec2 lowerClip = greaterThanEqual(editPos, ivec2(0));
        bvec2 upperClip = lessThan(editPos, imageSize(u_lightXluImage[0]).xy);
        if (all(bvec4(lowerClip, upperClip))){ //If inside the light image
            vec4 dynLightUnit = lightOfThisUnit(
                vec4(light.red, light.green, light.blue, light.xlu),
                lightPosPx,
                vec2(gl_LocalInvocationID.yz)
            );

            addAtomically(0, 0, editPos, dynLightUnit.rg);
            addAtomically(0, 1, editPos, dynLightUnit.ba);
        }
    }
}
