/**
 *  @author     Dubsky Tomas
 */
#version 460
#include <RealWorld/constants/Tile.glsl>
#include <RealWorld/constants/World.glsl>
#include <RealWorld/constants/Light.glsl>
#include <RealWorld/generation/external_shaders/snoise.glsl>
#include <RealWorld/drawing/shaders/calcInputsPll.glsl>
#include <RealWorld/drawing/shaders/AnalysisPC.glsl>

const int k_iAnalysisGroupSize = int(k_analysisGroupSize);

layout (local_size_x = k_iAnalysisGroupSize,
        local_size_y = k_iAnalysisGroupSize,
        local_size_z = 1
) in;

layout (set = 0, binding = k_lightXluImageBinding, r32ui)
    uniform restrict writeonly uimage2DArray u_lightXluImage[k_lightCellSizeCount];
layout (set = 0, binding = k_worldSamplerBinding)
    uniform usampler2DArray                  u_worldTex;
layout (set = 0, binding = k_blockLightAtlasBinding)
    uniform sampler2D                        u_blockLightAtlas;
layout (set = 0, binding = k_wallLightAtlasBinding)
    uniform sampler2D                        u_wallLightAtlas;

// Separate arrays to avoid bank conflicts
shared float s_lightR[k_iAnalysisGroupSize * k_iAnalysisGroupSize];
shared float s_lightG[k_iAnalysisGroupSize * k_iAnalysisGroupSize];
shared float s_lightB[k_iAnalysisGroupSize * k_iAnalysisGroupSize];
shared float s_xlu   [k_iAnalysisGroupSize * k_iAnalysisGroupSize];

void combineForMip(inout vec4 lightXlu, vec4 lightXluIn) {
    lightXlu.rgb += lightXluIn.rgb;
    lightXlu.a *= lightXluIn.a;
}

void reduceForMip(inout vec4 lightXlu) {
    lightXlu.rgb *= 0.5;
    lightXlu.a = sqrt(lightXlu.a);
}

void writeToImages(ivec2 loc, uint mip, vec4 lightXlu) {
    imageStore(u_lightXluImage[mip], ivec3(loc, 0), uvec4(packHalf2x16(lightXlu.rg)));
    imageStore(u_lightXluImage[mip], ivec3(loc, 1), uvec4(packHalf2x16(lightXlu.ba)));
}

void writeToShared(uvec2 loc, vec4 lightXlu) {
    uint index = loc.y * uint(k_analysisGroupSize) + loc.x;
    s_lightR[index] = lightXlu.r;
    s_lightG[index] = lightXlu.g;
    s_lightB[index] = lightXlu.b;
    s_xlu[index] = lightXlu.a;
}

vec4 readFromShared(uvec2 loc) {
    uint index = loc.y * uint(k_analysisGroupSize) + loc.x;
    return vec4(s_lightR[index], s_lightG[index], s_lightB[index], s_xlu[index]);
}

void main(){
    // Calculate position and init variables
    const ivec2 readBasePosTi =
        p_.analysisOffsetTi + (ivec2(gl_GlobalInvocationID) << k_lightMinCellTiBitShift);
    vec4 lightXlu = vec4(0.0, 0.0, 0.0, 1.0);

    // Analyze the thread's area = minimum cell size = mip 0
    for (int y = 0; y < k_lightMinCellTi; y++){
        for (int x = 0; x < k_lightMinCellTi; x++){
            // Fetch the tile
            ivec2 posAt = tiToAt(readBasePosTi + ivec2(x, y), p_.worldTexMask);
            uvec2 block = texelFetch(u_worldTex, ivec3(posAt, k_blockLayer), 0).xy & 0xff;
            uvec2 wall = texelFetch(u_worldTex, ivec3(posAt, k_wallLayer), 0).xy   & 0xff;

            // Process its translucency
            bool airBlock = isAirBlock(block.L_T);
            float tileXlu = airBlock ? 0.89 : 0.55;

            // Process it as a light source
            vec3 blockLight = texelFetch(u_blockLightAtlas, ivec2(block.yx), 0).rgb;
            vec3 wallLight = isAirWall(wall.L_T)
                             ? p_.skyLight.rgb
                             : texelFetch(u_wallLightAtlas, ivec2(wall.yx), 0).rgb;
            vec3 tileLight = airBlock ? wallLight : blockLight;

            lightXlu += vec4(tileLight, tileXlu);
        }
    }
    lightXlu *= 1.0 / (k_lightMinCellTi * k_lightMinCellTi);

    // Write mip 0
    writeToShared(gl_LocalInvocationID.xy, lightXlu);
    writeToImages(ivec2(gl_GlobalInvocationID), 0, lightXlu);

    // Generate mips
    ivec2 groupOffset = ivec2(gl_WorkGroupSize) * ivec2(gl_WorkGroupID);
    for (int mip = 1; mip < k_lightCellSizeCount; mip++) {
        barrier();
        int limit = k_iAnalysisGroupSize >> mip;
        bool act = gl_LocalInvocationID.x < limit && gl_LocalInvocationID.y < limit;
        uvec2 sharedVarLoc = gl_LocalInvocationID.xy << mip;
        if (act) {
            lightXlu = readFromShared(sharedVarLoc);
            combineForMip(lightXlu, readFromShared(sharedVarLoc + uvec2(0, 1)));
            combineForMip(lightXlu, readFromShared(sharedVarLoc + uvec2(1, 0)));
            combineForMip(lightXlu, readFromShared(sharedVarLoc + uvec2(1, 1)));
            reduceForMip(lightXlu);
        }
        barrier();
        if (act) {
            writeToShared(sharedVarLoc, lightXlu);
            writeToImages(
                (groupOffset >> mip) + ivec2(gl_LocalInvocationID.xy),
                mip,
                lightXlu
            );
        }
    }
}
