/**
 *  @author     Dubsky Tomas
 */
#version 460
#include <RealWorld/constants/Light.glsl>

layout (local_size_x = int(k_calcGroupSize),
        local_size_y = int(k_calcGroupSize),
        local_size_z = 1
) in;

layout (set = 0, binding = 0)
    uniform sampler2DArray             u_lightXluSampler;
layout (set = 0, binding = 1, rgba8)
    uniform restrict writeonly image2D u_shadowsImage;

vec2 g_analysisUvScale = 1.0 / textureSize(u_lightXluSampler, 0).xy;
const float k_uvOffset = float(k_lightMaxRangeTi >> k_lightMinCellTiBitShift) - 0.5;

const float k_piOver4   = 0.78539816339; 
const float k_piOver16  = 0.19634954084;
const float k_piOver32  = 0.09817477042;
const float k_piOver64  = 0.04908738521;
const float k_piOver128 = 0.0245436926;
const float k_piOver256 = 0.0122718463;
const float k_piOver512 = 0.00613592315;

const vec2 k_rayGBounds = vec2(78.0, 44.0);
const vec2 k_rayFBounds = vec2(43.0, 22.0);
const vec2 k_rayEBounds = vec2(21.0, 11.0);
const vec2 k_rayDBounds = vec2(10.0,  6.0);
const vec2 k_rayCBounds = vec2( 5.0,  3.0);
const vec2 k_rayBBounds = vec2( 2.0,  2.0);
const vec2 k_rayABounds = vec2( 1.0,  1.0);

vec4 sampleLightXlu(vec2 uv, float cascade) {
    return vec4(
        textureLod(u_lightXluSampler, vec3(uv, 0.0), cascade).xy,
        textureLod(u_lightXluSampler, vec3(uv, 1.0), cascade).xy
    );
}

void accumulate(inout vec3 accumulated, vec2 uv, float lightMult, float cascade) {
    vec4 lightXlu = sampleLightXlu(uv, cascade);
    accumulated = fma(accumulated, lightXlu.aaa, lightXlu.rgb * lightMult);
}

void ray(inout vec3 light, vec2 centerUv, vec2 dirUv, vec2 firstLast, float lightMult, int cascade) {
    vec2 uv = centerUv + dirUv * firstLast.y;
    for (float i = firstLast.y; i >= firstLast.x; i -= float(1 << cascade)){
        accumulate(light, uv, lightMult, cascade);
        uv -= dirUv * cascade;
    }
}

vec3 rayFG(vec2 centerUv, float a, float lightMult) {
    vec3 light = vec3(0.0);
    vec2 dirUv = vec2(cos(a), sin(a)) * g_analysisUvScale;
    ray(light, centerUv, dirUv, k_rayGBounds, lightMult, 2);
    ray(light, centerUv, dirUv, k_rayFBounds, lightMult, 1);
    return light;
}

vec3 rayE(vec2 centerUv, float a, float lightMult) {
    vec3 light = rayFG(centerUv, a - k_piOver128, lightMult * 0.5)
                 + rayFG(centerUv, a + k_piOver128, lightMult * 0.5);
    vec2 dirUv = vec2(cos(a), sin(a)) * g_analysisUvScale;
    ray(light, centerUv, dirUv, k_rayEBounds, lightMult, 1);
    return light;
}

vec3 rayCD(vec2 centerUv, float a, float lightMult) {
    vec3 light = rayE(centerUv, a - k_piOver64, lightMult * 0.5)
                 + rayE(centerUv, a + k_piOver64, lightMult * 0.5);
    vec2 dirUv = vec2(cos(a), sin(a)) * g_analysisUvScale;
    ray(light, centerUv, dirUv, k_rayDBounds, lightMult, 1);
    ray(light, centerUv, dirUv, k_rayCBounds, lightMult, 0);
    return light;
}

vec3 rayB(vec2 centerUv, float a, float lightMult) {
    vec3 light = rayCD(centerUv, a - k_piOver32, lightMult * 0.5)
                 + rayCD(centerUv, a + k_piOver32, lightMult * 0.5);
    vec2 dirUv = vec2(cos(a), sin(a)) * g_analysisUvScale;
    ray(light, centerUv, dirUv, k_rayBBounds, lightMult, 0);
    return light;
}

vec3 rayA(vec2 centerUv, float a, float lightMult) {
    vec3 light = rayB(centerUv, a - k_piOver16, lightMult * 0.5)
                 + rayB(centerUv, a + k_piOver16, lightMult * 0.5);
    vec2 dirUv = vec2(cos(a), sin(a)) * g_analysisUvScale;
    ray(light, centerUv, dirUv, k_rayABounds, lightMult, 0);
    return light;
}

/// Return value is in range (0, 1)
float tonemap(float intensity) {
    return smoothstep(0.0, 5.0, intensity);
}

float correctGamma(float color) {
    return pow(color, 1.0/3.0);
}

void main() {
    // Calculate position and init variables
    const ivec2 ID = ivec2(gl_GlobalInvocationID);
    vec3 total = vec3(0.0);
    const vec2 centerUv = (vec2(ID) + k_uvOffset) * g_analysisUvScale;

    // Eight tree-like rays, each sums 45 degrees
    for (float a = k_piOver256; a < 6.2; a += k_piOver4){
        total += rayA(centerUv, a, 16.0);
    }

    // The center unit
    total += sampleLightXlu(centerUv, 0.0).rgb;

    float intensity = total.x + total.y + total.z;

    vec4 final = vec4(0.0, 0.0, 0.0, 1.0 - correctGamma(tonemap(intensity)));
    imageStore(u_shadowsImage, ID, final);
}
