/**
 *  @author     Dubsky Tomas
 */
#version 460
#include <RealWorld/constants/Light.glsl>
#include <RealWorld/drawing/shaders/LightSweepPC.glsl>

layout (local_size_x = int(k_lightSweepGroupSize),
        local_size_y = int(k_lightSweepGroupSize),
        local_size_z = 1
) in;

layout (set = 0, binding = 0)
    uniform sampler2DArray             u_lightXluSampler;
layout (set = 0, binding = 1, rgba8)
    uniform restrict writeonly image2D u_shadowsImage;

const float k_piOver4   = 0.78539816339; 
const float k_piOver16  = 0.19634954084;
const float k_piOver32  = 0.09817477042;
const float k_piOver64  = 0.04908738521;
const float k_piOver128 = 0.0245436926;
const float k_piOver256 = 0.0122718463;
const float k_piOver512 = 0.00613592315;

const vec2 k_rayGNearFar = vec2(44.0, 78.0);
const vec2 k_rayFNearFar = vec2(22.0, 43.0);
const vec2 k_rayENearFar = vec2(11.0, 21.0);
const vec2 k_rayDNearFar = vec2( 6.0, 10.0);
const vec2 k_rayCNearFar = vec2( 3.0,  5.0);
const vec2 k_rayBNearFar = vec2( 2.0,  2.0);
const vec2 k_rayANearFar = vec2( 1.0,  1.0);

const int k_rayGCascade = 2;
const int k_rayFCascade = 1;
const int k_rayECascade = 1;
const int k_rayDCascade = 1;
const int k_rayCCascade = 0;
const int k_rayBCascade = 0;
const int k_rayACascade = 0;

const float k_treeRayBaseLightMult = 16.0; //< Light power multiplier at trunk

vec4 sampleLightXlu(vec2 uv, float cascade) {
    return vec4(
        textureLod(u_lightXluSampler, vec3(uv, 0.0), cascade).xy,
        textureLod(u_lightXluSampler, vec3(uv, 1.0), cascade).xy
    );
}

void accumulate(inout vec3 accumulated, vec2 uv, float lightMult, float cascade) {
    vec4 lightXlu = sampleLightXlu(uv, cascade);
    accumulated = fma(accumulated, lightXlu.aaa, lightXlu.rgb * lightMult);
}

void ray(inout vec3 light, vec2 centerUv, vec2 dirUv, vec2 nearFar, float lightMult, int cascade) {
    vec2 uv = centerUv + dirUv * nearFar.y;
    float cascadeDiameter = float(1 << cascade);
    for (float i = nearFar.y; i >= nearFar.x; i -= cascadeDiameter){
        accumulate(light, uv, lightMult, cascade);
        uv -= dirUv * cascadeDiameter;
    }
}

vec3 rayFG(vec2 centerUv, float a, float lightMult) {
    vec3 light = vec3(0.0);
    vec2 dirUv = vec2(cos(a), sin(a)) * p_.uvScale;
    ray(light, centerUv, dirUv, k_rayGNearFar, lightMult, k_rayGCascade);
    ray(light, centerUv, dirUv, k_rayFNearFar, lightMult, k_rayFCascade);
    return light;
}

vec3 rayE(vec2 centerUv, float a, float lightMult) {
    vec3 light = rayFG(centerUv, a - k_piOver128, lightMult * 0.5)
                 + rayFG(centerUv, a + k_piOver128, lightMult * 0.5);
    vec2 dirUv = vec2(cos(a), sin(a)) * p_.uvScale;
    ray(light, centerUv, dirUv, k_rayENearFar, lightMult, k_rayECascade);
    return light;
}

vec3 rayCD(vec2 centerUv, float a, float lightMult) {
    vec3 light = rayE(centerUv, a - k_piOver64, lightMult * 0.5)
                 + rayE(centerUv, a + k_piOver64, lightMult * 0.5);
    vec2 dirUv = vec2(cos(a), sin(a)) * p_.uvScale;
    ray(light, centerUv, dirUv, k_rayDNearFar, lightMult, k_rayDCascade);
    ray(light, centerUv, dirUv, k_rayCNearFar, lightMult, k_rayCCascade);
    return light;
}

vec3 rayB(vec2 centerUv, float a, float lightMult) {
    vec3 light = rayCD(centerUv, a - k_piOver32, lightMult * 0.5)
                 + rayCD(centerUv, a + k_piOver32, lightMult * 0.5);
    vec2 dirUv = vec2(cos(a), sin(a)) * p_.uvScale;
    ray(light, centerUv, dirUv, k_rayBNearFar, lightMult, k_rayBCascade);
    return light;
}

vec3 rayA(vec2 centerUv, float a, float lightMult) {
    vec3 light = rayB(centerUv, a - k_piOver16, lightMult * 0.5)
                 + rayB(centerUv, a + k_piOver16, lightMult * 0.5);
    vec2 dirUv = vec2(cos(a), sin(a)) * p_.uvScale;
    ray(light, centerUv, dirUv, k_rayANearFar, lightMult, k_rayACascade);
    return light;
}

/// Return value is in range (0, 1)
float tonemap(float intensity) {
    return smoothstep(0.0, 5.0, intensity);
}

vec3 tonemapColor(vec3 light) {
    float intenMin = min(light.x, min(light.y, light.z));
    return smoothstep(intenMin, intenMin * 2.0f + 1.0f, light);
}

float correctGamma(float color) {
    return pow(color, 1.0/3.0);
}

void main() {
    // Calculate position and init variables
    const ivec2 ID = ivec2(gl_GlobalInvocationID);
    vec3 light = vec3(0.0);
    const vec2 centerUv = (vec2(ID) + p_.uvOffset) * p_.uvScale;

    // Eight tree-like rays, each sums 45 degrees
    {
        float a = k_piOver256;
        for (int i = 0; i < 8; ++i, a += k_piOver4) {
            light += rayA(centerUv, a, k_treeRayBaseLightMult);
        }
    }

    // The center unit
    light += sampleLightXlu(centerUv, 0.0).rgb * k_treeRayBaseLightMult;

    float intenSum = light.x + light.y + light.z;

    vec4 final = vec4(tonemapColor(light), 1.0 - correctGamma(tonemap(intenSum)));
    imageStore(u_shadowsImage, ID, final);
}
