#pragma once
#ifndef LM_EXPRESSION_LIST

#define LM_EXPRESSION_LIST(m)   \
    m(MMENU, LOAD_TEXTURE) \
	m(MMENU, SELECT_TEXTURE) \
	m(MMENU, TEXTURE_FILTERS) \
	\
	m(MMENU, OVERLAP) \
	\
	m(MMENU, SAVE_AS) \
	m(MMENU, SAVE_AS_EXPLORER) \
	m(MMENU, SAVE) \
	\
	\
	\
	m(RTI, FORMAT_TYPE) \
	m(RTI, NORMALIZED) \
	m(RTI, INTEGRAL) \
	\
	m(RTI, FORMAT_SIGN) \
	m(RTI, UNSIGNED) \
	m(RTI, SIGNED) \
	\
	m(RTI, MIN_FILTER) \
	m(RTI, MIN_NEAREST) \
	m(RTI, MIN_LINEAR) \
	m(RTI, NEAREST_MIPMAP_NEAREST) \
	m(RTI, NEAREST_MIPMAP_LINEAR) \
	m(RTI, LINEAR_MIPMAP_NEAREST) \
	m(RTI, LINEAR_MIPMAP_LINEAR) \
	\
	m(RTI, MAG_FILTER) \
	m(RTI, MAG_NEAREST) \
	m(RTI, MAG_LINEAR) \
	\
	m(RTI, WRAP_STYLE_X) \
	m(RTI, WRAP_STYLE_Y) \
	m(RTI, CLAMP_TO_EDGE) \
	m(RTI, CLAMP_TO_BORDER) \
	m(RTI, REPEAT_NORMALLY) \
	m(RTI, REPEAT_MIRRORED) \
	\
	m(RTI, BORDER_COLOUR) \
	\
	\
	\
	m(RTI, N_SUBIMAGES) \
	m(RTI, N_SPRITES) \
	\
	m(RTI, SUBIMAGE_DIMS) \
	m(RTI, SUBIMAGE_PIVOT) \
	\
	m(RTI, X_COMPONENT) \
	m(RTI, Y_COMPONENT) \
	m(RTI, CENTER) \

#endif // !LM_EXPRESSION_LIST
#include <RealEngine/utility/LanguageManager.hpp>