name: Create draft release

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened]

jobs:
  create-branch-release:
    runs-on: windows-2022
    steps:
    - name: Create branch release
      run: >
        gh release create ${{ github.head_ref }}
        --draft --prerelease
        --repo ZADNE/RealWorld
        --target ${{ github.head_ref }}
        --title "RealWorld ${{ github.head_ref }}"
      env:
        GH_TOKEN: ${{ github.token }}